import { useEffect, useState } from "react";
import { Button, PageHeader, StatusPill, Toggle } from "../components/ui";
import { diagnosticsService, type HealthSnapshot } from "../services/diagnosticsService";
import { workspaceService } from "../services/workspaceService";
import type { SourceConfig } from "../types/domain";

export function SettingsPage() {
  const [sources, setSources] = useState<SourceConfig[]>([]); const [activeSection, setActiveSection] = useState("Sources"); const [scanOnStart, setScanOnStart] = useState(true); const [autoCheck, setAutoCheck] = useState(true); const [health, setHealth] = useState<HealthSnapshot | null>(null); const [healthError, setHealthError] = useState<string | null>(null);
  useEffect(() => { void workspaceService.getSources().then(setSources); void diagnosticsService.getHealth().then(setHealth).catch((error: unknown) => setHealthError(diagnosticsService.formatError(error))); }, []);
  return <section className="page"><PageHeader title="Settings" subtitle="配置 Sources、更新策略与本地安全边界。" actions={<Button variant="primary">保存设置</Button>} />
    <div className="workbench settings-workbench"><aside className="panel-surface settings-nav">{["通用", "Sources", "更新策略", "安全"].map((item) => <button className={activeSection === item ? "subnav-item active" : "subnav-item"} key={item} onClick={() => setActiveSection(item)} type="button"><span>{item}</span></button>)}</aside>
    <section className="panel-surface settings-main"><div className="bundle-heading compact"><div><span className="eyebrow">{activeSection}</span><h2>Skill Sources</h2><p>只从明确配置的来源发现 Skill，不做全盘扫描。</p></div></div><div className="source-list">{sources.map((source) => <div className="source-card" key={source.id}><i className="source-icon">↗</i><span><strong>{source.name}</strong><small>{source.description}</small></span><span className="source-detail">{source.detail}</span><StatusPill tone={source.enabled ? "green" : "gray"}>{source.enabled ? "已启用" : "已关闭"}</StatusPill></div>)}</div><div className="settings-options"><div><span><strong>启动时扫描</strong><small>仅扫描 Adapter 与用户配置的根目录。</small></span><Toggle checked={scanOnStart} onChange={setScanOnStart} /></div><div><span><strong>自动检查更新</strong><small>只检查，不自动覆盖 Library 或 Agent。</small></span><Toggle checked={autoCheck} onChange={setAutoCheck} /></div><div><span><strong>默认更新策略</strong><small>检测到上游变化后由用户确认应用。</small></span><button className="select-button" type="button">手动应用 <b>⌄</b></button></div></div></section>
    <aside className="panel-surface inspector settings-inspector"><div className="inspector-title simple"><div><h2>当前环境</h2><p>M0 Diagnostics 已收进设置页。</p></div></div>{health ? <><div className="diagnostic-status"><span><i className="health-dot" />Desktop Bridge</span><strong>Connected</strong></div><div className="diagnostic-status"><span><i className="health-dot" />SQLite</span><strong>{health.databaseOk ? "Ready" : "Error"}</strong></div><dl className="detail-list compact-list"><div><dt>App</dt><dd>v{health.appVersion}</dd></div><div><dt>DB Write Test</dt><dd>{health.counter}</dd></div></dl><div className="path-card"><span>Database</span><code title={health.databasePath}>{health.databasePath}</code></div><div className="path-card"><span>Local Log</span><code title={health.logPath}>{health.logPath}</code></div></> : <div className="diagnostic-offline"><StatusPill tone="gray">Desktop only</StatusPill><p>{healthError ? "浏览器预览无法调用 Tauri Bridge。" : "正在读取本地诊断信息…"}</p></div>}<div className="safety-note"><span>✦</span><p><strong>安全边界</strong><br />管理器扫描和同步 Skill 时不会执行 scripts。</p></div></aside></div>
  </section>;
}
